Add input/output filter + weaken WPlayerInvPanel's components' protection
CottonMC/LibGui pull request #209
Opened 2023-07-31 21:20 UTC by Luligabi1

- Deprecates `WItemSlot`'s filter system in favor of input and output filters;
    - The test mod is updated to test this.
- Weaken `WPlayerInvPanel`'s components (`inv`, `hotbar` and `label`) from `private` to `protected;
- Bump some dependencies, as the test mod wouldn't launch without it.

2023-08-01 08:23 UTC, Juuxel requested changes

2023-08-01 08:23 UTC, Juuxel commented on gradle.properties
>  	yarn_mappings=1.20+build.1
If you bump the game version, you should also update Yarn to the latest version for that MC version.

2023-08-01 08:23 UTC, Juuxel commented on src/main/java/io/github/cottonmc/cotton/gui/widget/WItemSlot.java
>  	public Predicate<ItemStack> getFilter() {
Deprecated members should have `@Deprecated`.

2023-08-01 08:23 UTC, Juuxel commented on src/main/java/io/github/cottonmc/cotton/gui/widget/WPlayerInvPanel.java
> +	protected final WItemSlot inv;
1. Needlessly abbreviated names like `inv` shouldn't be exposed as APIs, it needs a human-readable name
2. Public APIs should have javadoc

2023-08-01 08:23 UTC, Juuxel commented on src/testMod/java/io/github/cottonmc/test/TestDescription.java
> +
Don't do formatting changes like this.

2023-08-02 15:49 UTC, Juuxel requested changes
LGTM with these small changes

2023-08-02 15:49 UTC, Juuxel commented on gradle.properties
This file should use the original formatting (however ugly it is)

2023-08-02 15:49 UTC, Juuxel commented on src/main/java/io/github/cottonmc/cotton/gui/ValidatedSlot.java
> +	 * The default {@linkplain #setInputFilter(Predicate)  item filter} that allows all items.
```suggestion
	 * The default {@linkplain #setInputFilter(Predicate) item filter} that allows all items.
```

2023-08-02 15:49 UTC, Juuxel commented on src/testMod/java/io/github/cottonmc/test/TestDescription.java
>  		root.add(new WButton(testIcon, Text.literal("Button C")), 0, 5, 4, 1);
```suggestion
		TextureIcon testIcon = new TextureIcon(new Texture(new Identifier("libgui-test", "icon.png")));
		root.add(new WButton(testIcon, Text.literal("Button C")), 0, 5, 4, 1);
```

2023-08-02 19:38 UTC, Juuxel commented on gradle.properties
It still has formatting changes but I guess I can fix those when merging

2023-08-02 19:38 UTC, Juuxel approved these changes

2023-08-03 02:46 UTC, Luligabi1 commented on gradle.properties
oops, I ended up picking it from my previous-previous commit instead of the original. Sorry!

2023-09-09 09:25 UTC, merged