WScrollBar.paint update
CottonMC/LibGui pull request #212
Opened 2023-09-01 11:52 UTC by LopyMine

Updated paint method in WScrollBar widget
Added new textures for WScrollBar
Added ScrollBarTestGui to TestMod

2023-09-03 10:49 UTC, Juuxel requested changes

2023-09-03 10:49 UTC, Juuxel commented on src/main/java/io/github/cottonmc/cotton/gui/widget/WScrollBar.java
> +	private static final NinePatchBackgroundPainter focus = createNinePatch(new Identifier(LibGuiCommon.MOD_ID, "textures/gui/scroll_bar/scroll_bar_focus.png"));
1. Static final fields should be in `CONSTANT_CASE`
2. This code will fail to load on a dedi server. You should store these in a `private static final` inner class annotated with `@Environment(CLIENT)` like in `WTabPanel`:
https://github.com/CottonMC/LibGui/blob/e7a36835ff95ac045bbeac156a105c16b4d23df2/src/main/java/io/github/cottonmc/cotton/gui/widget/WTabPanel.java#L442-L456

2023-09-03 10:49 UTC, Juuxel commented on src/main/java/io/github/cottonmc/cotton/gui/widget/WScrollBar.java
>  	private static void drawBeveledOutline(DrawContext context, int x, int y, int width, int height, int topleft, int bottomright) {
Is this method still used somewhere? If yes, it shouldn't be deprecated, and if not, it should be removed.

2023-09-03 10:49 UTC, Juuxel commented on src/testMod/java/io/github/cottonmc/test/client/ScrollBarTestGui.java
> +	private boolean darkMode = false;
This field is never written to, so I don't really see a point of having it. You could add a toggle button that changes its value, or just rely on the global light/dark mode setting.

2023-09-03 12:02 UTC, Juuxel reviewed
I'd prefer a flat layout for the textures instead of `dark` being a subdirectory so that it'd match the other widgets better, eg:
- `scroll_bar/background_light.png`
- `scroll_bar/background_dark.png`
Additionally, the `scroll_bar_` prefix can be dropped from `background` and `focus`.

(Another naming nit: the `scroll_bar(_pressed|_hovered)` textures should probably use `thumb` as the term since it's used by the scroll bar and slider code. Doesn't really matter though.)

2023-09-03 13:39 UTC, LopyMine commented
Okay, I rendered directly via NinePatch.draw, I hope I didn't miss anything.

2023-09-04 11:20 UTC, Juuxel commented on gradle.properties
This file shouldn't have the formatting changes

2023-09-04 11:23 UTC, LopyMine commented on gradle.properties
wanted to launch minecraft, but to launch it was necessary to update the version of minecraft above, but after that I gave up on this idea) And I accidentally committed this file...

2023-09-04 11:45 UTC, LopyMine commented
I made a commit in which I rolled back the gradle.properties file to the original, now everything should be fine

2023-09-05 14:58 UTC, LopyMine commented
I remembered here, the user scrolling through the list missed some components, and I would like to have a WScrollBar.setScrollingSpeed(int) method, can I add this method to WScrollBar?

2023-09-09 09:31 UTC, Juuxel commented
@LopyMine That is a bit unrelated to this PR so I feel like it could be its own small PR.

2023-09-09 10:28 UTC, LopyMine commented
ok, I'll think about adding this as a separate PR later

2023-09-09 11:12 UTC, Juuxel commented on src/main/java/io/github/cottonmc/cotton/gui/widget/WScrollBar.java
> +	final static class Painters {
Nit:
```suggestion
	static final class Painters {
```

2023-09-09 11:12 UTC, Juuxel commented on src/main/java/io/github/cottonmc/cotton/gui/widget/WScrollBar.java
The formatting changes to unrelated methods should be reverted here to minimise the diff

2023-09-09 11:12 UTC, Juuxel commented on src/testMod/java/io/github/cottonmc/test/client/ScrollBarTestGui.java
> +
Nit:
```suggestion
```

2023-09-09 11:20 UTC, LopyMine commented
Okay, I fixed it in a new commit.

2023-09-09 13:45 UTC, Juuxel approved these changes
Looks great, thanks for the PR!

2023-09-09 13:52 UTC, merged